### ISSUE TITLE
[Question] Why mappers instead of plugin

### ISSUE THREAD

**Issue by CTOJoe** [Urigo/WhatsApp-Clone-Server#105]
Is there a specific reason that the [server plugin](https://graphql-code-generator.com/docs/plugins/typescript-server) is not used vs [manually mapping](https://github.com/Urigo/WhatsApp-Clone-server/blob/796953cdf7122f579e1b8fb37984de3ddc5d0882/codegen.yml#L12-L16) each entity? GraphQL code generator supports this automatically with the plugin. 

Additionally, manual mapping will also become more difficult if [connections, nodes, and edges](https://blog.apollographql.com/explaining-graphql-connections-c48b7c3d6976) are ever implemented by this project in the future.

**Comment by dotansimha** [comment]
Hi @CTOJoe ! 
The `typescript-server` is not longer relevant, it's deprecated, and only `typescript` should be in use. See the updated file here: https://github.com/Urigo/WhatsApp-Clone-Server/blob/master/codegen.yml 

The `typescript-resolvers` use the base types from `typescript`, and in order to override and use custom types, we need to provide these `mappers`.

GraphQL only defines how your external API looks, and your internal models are usually different, so you can use `mappers` to replace specific GraphQL types with your models (it only effects the resolvers plugin). The GraphQL Code Generator does not do automatic mapping, because it can't tell which model type to use.
